import { motion } from "framer-motion";
import { ShoppingBag, Users, Package, Ticket, Image as ImageIcon } from "lucide-react";

const ACTIVITIES = [
  { id: 1, title: "New product added", desc: "Organic Bananas was added to inventory", time: "10 mins ago", type: "product", icon: <ShoppingBag className="size-4" /> },
  { id: 2, title: "Coupon created", desc: "SUMMER50 was generated by Admin", time: "1 hour ago", type: "coupon", icon: <Ticket className="size-4" /> },
  { id: 3, title: "Banner updated", desc: "Homepage hero banner replaced", time: "2 hours ago", type: "banner", icon: <ImageIcon className="size-4" /> },
  { id: 4, title: "New customer registered", desc: "john.doe@example.com signed up", time: "5 hours ago", type: "customer", icon: <Users className="size-4" /> },
  { id: 5, title: "Inventory updated", desc: "Received 500 units of Fresh Milk", time: "1 day ago", type: "inventory", icon: <Package className="size-4" /> },
];

export function RecentActivityFeed() {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.5, duration: 0.5 }}
      className="bg-white p-6 rounded-[20px] shadow-sm border border-slate-100 w-full"
    >
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-lg font-bold text-slate-800 tracking-tight">Recent Activity</h3>
      </div>

      <div className="space-y-6">
        {ACTIVITIES.map((activity, idx) => (
          <div key={activity.id} className="flex gap-4 relative">
            {/* Timeline line */}
            {idx !== ACTIVITIES.length - 1 && (
              <div className="absolute left-5 top-10 bottom-[-24px] w-px bg-slate-100" />
            )}
            
            <div className={`size-10 rounded-full flex items-center justify-center shrink-0 z-10 ${
              activity.type === 'product' ? 'bg-emerald-50 text-emerald-600' :
              activity.type === 'coupon' ? 'bg-amber-50 text-amber-600' :
              activity.type === 'banner' ? 'bg-purple-50 text-purple-600' :
              activity.type === 'customer' ? 'bg-blue-50 text-blue-600' : 'bg-indigo-50 text-indigo-600'
            }`}>
              {activity.icon}
            </div>
            
            <div>
              <div className="text-sm font-bold text-slate-800 mb-0.5">{activity.title}</div>
              <div className="text-xs font-medium text-slate-500 mb-1">{activity.desc}</div>
              <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">{activity.time}</div>
            </div>
          </div>
        ))}
      </div>
    </motion.div>
  );
}
